# LISTA DE PANDAS-2

**Importe as bibliotecas necessárias**

**Importe os dados sobre as ações, que estão nos arquivos "carteira.csv" e "ativos.csv".**

In [3]:
##### SEU CODIGO COMECA AQUI #####
import pandas as pd
import numpy as np
import random

ativo = pd.read_csv("ativos copy.csv", index_col = 0, parse_dates = True)
carteira = pd.read_csv("carteiras.csv", index_col = 5, parse_dates = ["data"])

**Exercício 1: Filtragem de dados**

Filtre o Dataframe a partir de 5 ações, de modo que essas ações podem ser escolhidas pela sua preferência ou de forma aleatória. Após a filtragem, salve em uma nova variável.

In [63]:
##### SEU CODIGO COMECA AQUI #####
acoes = random.choices(ativo.columns, k=5)
acoes

['ALSO3', 'UGPA3', 'ANIM3', 'SYNE3', 'TIMS3']

In [64]:
df_acoes = ativo.filter(items = acoes, axis = 1)
df_acoes

                 ALSO3       UGPA3       ANIM3       SYNE3       TIMS3
data
2021-12-31  100.000000  100.000000  100.000000  100.000000  100.000000
2022-01-03   95.198523   97.111417   94.285714  100.833333   96.045627
2022-01-04   93.628809   93.466300   88.333333  101.388889   97.490494
2022-01-05   88.457987   90.990371   83.095238   96.250000   96.577947
2022-01-06   87.119114   89.683631   84.642857   93.055556   95.893536
...                ...         ...         ...         ...         ...
2022-07-25   78.297132   91.799236   55.476190   61.840969   97.626556
2022-07-26   77.026686   89.287138   54.047619   60.473478   97.240681
2022-07-27   79.379364   92.516978   55.952381   61.233195   95.697178
2022-07-28   80.320436   91.655688   54.166667   62.904573   97.472206
2022-07-29   79.379364   91.081494   53.333333   62.752629   97.163506

[146 rows x 5 columns]

**Exercício 2: Retorno**

Utilizando o Dataframe filtrado no exercício anterior, calcule o retorno diário dessas 5 ações. Para isso, utilize o método `pct_change`. Além disso, mude o nome das colunas para o nome da ação seguido de uma hashtag, por exemplo, 'BBAS3#'.

salve um uma variável chamada `retorno`.

In [65]:
##### SEU CODIGO COMECA AQUI #####
retorno = df_acoes.pct_change()

for i in retorno.keys():
    retorno[i + "#"] = retorno[i]
    del retorno[i]

retorno = pd.DataFrame(retorno)
retorno

              ALSO3#    UGPA3#    ANIM3#    SYNE3#    TIMS3#
data
2021-12-31       NaN       NaN       NaN       NaN       NaN
2022-01-03 -0.048015 -0.028886 -0.057143  0.008333 -0.039544
2022-01-04 -0.016489 -0.037535 -0.063131  0.005510  0.015044
2022-01-05 -0.055227 -0.026490 -0.059299 -0.050685 -0.009360
2022-01-06 -0.015136 -0.014361  0.018625 -0.033189 -0.007087
...              ...       ...       ...       ...       ...
2022-07-25 -0.002398  0.026485  0.019694 -0.007317 -0.019380
2022-07-26 -0.016226 -0.027365 -0.025751 -0.022113 -0.003953
2022-07-27  0.030544  0.036174  0.035242  0.012563 -0.015873
2022-07-28  0.011855 -0.009310 -0.031915  0.027295  0.018548
2022-07-29 -0.011716 -0.006265 -0.015385 -0.002415 -0.003167

[146 rows x 5 columns]

**Exercício 3: Ordenar**

Utilizando o método `describe`, analise a média de retorno das ações. Após isso, organize os dados de tal modo que as ações sejam apresentadas de forma decrescente, isto é, a ação que teve a maior média de retorno para a  ação que teve a menor média de retorno.

  
   *Lembre-se de definir o parâmetro 'ascending' e 'by'.*

In [66]:
##### SEU CODIGO COMECA AQUI #####
retorno.describe().sort_values(by='mean', axis=1, ascending=False)

           TIMS3#      UGPA3#      ALSO3#      SYNE3#      ANIM3#
count  145.000000  145.000000  145.000000  145.000000  145.000000
mean    -0.000083   -0.000289   -0.001367   -0.002934   -0.003801
std      0.015245    0.026761    0.021228    0.023513    0.032552
min     -0.039544   -0.077083   -0.057289   -0.077477   -0.073171
25%     -0.009654   -0.017869   -0.013827   -0.016129   -0.029083
50%     -0.001476   -0.004886   -0.002703   -0.002415   -0.004167
75%      0.010386    0.016432    0.011809    0.009685    0.019694
max      0.050558    0.059117    0.053319    0.077496    0.103015

**Exercício 4: Manipulação** 

Para a ação que obteve a maior média de retonos no périodo apresentado, crie uma coluna chamada `acima_da_media_x`, sendo o 'x' o nome da ação. Sendo assim, essa coluna deve conter valores booleanos, `True` caso a ação esteja com o preço acima da sua média e `False` caso o preço da ação seja menor ou igual a média. Feito isso, printe apenas os dados que são iguais a `True`. 

*Dessa forma, poderemos saber em quais dias que a ação obteve um retorno maior que a sua média*

In [70]:
##### SEU CODIGO COMECA AQUI #####
acima_da_media = []
nome_acao = retorno.columns[0]
for dia in retorno[nome_acao]:
    if dia > -0.000083:
         acima_da_media.append(True)
    else:
        acima_da_media.append(False)

retorno[f'acima_da_media_{nome_acao}'] = acima_da_media
retorno[retorno[f'acima_da_media_{nome_acao}'] == True]

,ALSO3#,UGPA3#,ANIM3#,SYNE3#,TIMS3#,acima_da_media_TIMS3#
data,,,,,,
2022-01-04,-0.016489,-0.037535,-0.063131,0.005510,0.015044,True
2022-01-11,0.016593,0.016432,0.016393,-0.007669,0.006499,True
2022-01-12,0.053319,0.039261,0.021994,0.034003,0.008071,True
2022-01-13,0.012913,-0.008889,-0.017217,0.001495,0.017614,True
2022-01-17,-0.030409,-0.022796,-0.008596,0.001475,0.024545,True
...,...,...,...,...,...,...
2022-07-06,-0.004245,0.006814,0.044619,0.009685,0.005368,True
2022-07-07,0.012789,0.004230,0.103015,-0.002398,0.031274,True
2022-07-19,0.004356,-0.000832,-0.039387,0.019851,0.014763,True
2022-07-21,0.012210,-0.003145,0.002160,-0.007264,0.001552,True
2022-07-28,0.011855,-0.009310,-0.031915,0.027295,0.018548,True

**Exercício 5: Proporção**

Após descobrir em quais dias que a ação teve um retorno maior que a sua média, calcule qual foi a proporção em que isso aconteceu, ou seja, a proporção de dias que esteve acima da média em relação ao total de dias.

*printe essa proporção da seguinte forma: 'A proporção de dias acima da média foi de X%', sendo 'X' a proporção. Arredonde em duas casa decimais o valor encontrado*

In [75]:
##### SEU CODIGO COMECA AQUI #####
dias_acima = retorno[retorno[f'acima_da_media_{nome_acao}'] == True].count()
dias_total = retorno.count()

proporcao = dias_acima[f'acima_da_media_{nome_acao}'] / dias_total[f'acima_da_media_{nome_acao}']
proporcao

0.4315068493150685

**Exercício 6: Junção**

Por fim, faça a união **total** do dataframe contendo cinco primeiras ações escolhidas  inicialmente (no ex. 1) com o dataframe contendo os retornos dessas ações (criado no ex.2). Espera-se um único dataframe como resposta.

In [82]:
##### SEU CODIGO COMECA AQUI #####
for i in df_acoes.keys():
    df_acoes[i + "#"] = df_acoes[i]
    del df_acoes[i]

                ALSO3#      UGPA3#      ANIM3#      SYNE3#      TIMS3#
data
2021-12-31  100.000000  100.000000  100.000000  100.000000  100.000000
2022-01-03   95.198523   97.111417   94.285714  100.833333   96.045627
2022-01-04   93.628809   93.466300   88.333333  101.388889   97.490494
2022-01-05   88.457987   90.990371   83.095238   96.250000   96.577947
2022-01-06   87.119114   89.683631   84.642857   93.055556   95.893536
...                ...         ...         ...         ...         ...
2022-07-25   78.297132   91.799236   55.476190   61.840969   97.626556
2022-07-26   77.026686   89.287138   54.047619   60.473478   97.240681
2022-07-27   79.379364   92.516978   55.952381   61.233195   95.697178
2022-07-28   80.320436   91.655688   54.166667   62.904573   97.472206
2022-07-29   79.379364   91.081494   53.333333   62.752629   97.163506

[146 rows x 5 columns]

In [83]:
df_acoes.merge(retorno, how='outer')

,ALSO3#,UGPA3#,ANIM3#,SYNE3#,TIMS3#,acima_da_media_TIMS3#
0,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
1,95.198523,97.111417,94.285714,100.833333,96.045627,NaN
2,93.628809,93.466300,88.333333,101.388889,97.490494,NaN
3,88.457987,90.990371,83.095238,96.250000,96.577947,NaN
4,87.119114,89.683631,84.642857,93.055556,95.893536,NaN
...,...,...,...,...,...,...
287,-0.002398,0.026485,0.019694,-0.007317,-0.019380,False
288,-0.016226,-0.027365,-0.025751,-0.022113,-0.003953,False
289,0.030544,0.036174,0.035242,0.012563,-0.015873,False
290,0.011855,-0.009310,-0.031915,0.027295,0.018548,True
291,-0.011716,-0.006265,-0.015385,-0.002415,-0.003167,False